import { JWT } from "google-auth-library";
import { GoogleSpreadsheet } from "google-spreadsheet";
import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest) {
  const url = req.url
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL,
    key: process.env.NEXT_PUBLIC_GOOGLE_PRIVATE_KEY!.replace(/\\n/g, "\n"),
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
  });

  const doc = new GoogleSpreadsheet(
    process.env.NEXT_PUBLIC_GOOGLE_SHEETS_ID!,
    serviceAccountAuth
  );

  await doc.loadInfo(); // loads document properties and worksheets

  const sheet = doc.sheetsByIndex[0];
  const rows = await sheet.getRows();

  const data: {
    nim: string;
    name: string;
    score: string;
  }[] = [];

  await rows.forEach(async (row) => {
    if (row.get("Fase Pencerahan") === "-") return;

    data.push({
      nim: row.get("NIM"),
      name: row.get("Nama"),
      score: row.get("Fase Pencerahan"),
    });
  });

  const sortedProfileboard = data.sort(
    (a, b) => parseFloat(b.score) - parseFloat(a.score)
  );

  return NextResponse.json(sortedProfileboard);
}
