import "./globals.css";

import { Inter } from "next/font/google";

import Navbar from "@/components/layout/navbar";
import { Toaster } from "@/components/ui/toast/toaster";
import { NextAuthProvider } from "@/context/auth-provider";
import { QueryProvider } from "@/context/query-provider";
import { ThemeProvider } from "@/context/theme-provider";

const font = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Intellektuelle Schulle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body
        className={`${font.className} dark overflow-y-auto min-h-screen h-full`}
      >
        <NextAuthProvider>
          <QueryProvider>
            <ThemeProvider attribute="class" defaultTheme="dark">
              {children}
              <Toaster />
            </ThemeProvider>
          </QueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
